### ISSUE TITLE
.ml and .re files do not compile to .js files

### ISSUE THREAD

**Issue by pavsidhu** [jtberglund/gatsby-plugin-reason#1]
Using the current latest version of Gatsby (1.9), I am not able to compile either .ml or .re files after following the setup guide in the README.md.

I understand this is a vague issue, but do you have any ideas as to why? Thanks

**Comment by jtberglund** [comment]
Sorry for the delayed response.

I just published a new version which fixes some dependency issues, and I added some clarification to the README to make sure that `bs-platform` is linked correctly. Try updating to the latest version and re-building.

Also make sure that `bs-platform` is installed globally and linked, or install it as a dependency.

```
npm i -g bs-platform
npm link bs-platform
```
or
```
npm i bs-platform
```

At the moment, the output from `bs-platform` is not piped to the console. I'm currently working on a way to show the status of the build in the console, but right now it will fail silently if the build fails. 

After running `gatsby develop`, if you see that `lib/bs` is created, but the folder is otherwise empty, or if you see an error that says
```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.
```

then that means `bs-platform` failed to build. You can try running `bsb -make-world` at that point, and that should provide a more detailed error message.

**Comment by pavsidhu** [comment]
It seemed that I hadn't had `bs-platform` installed. Thanks for the fix, great work on the plugin 😄
